
name: luminixdx_web_ui_en
description: A Flutter Web UI for LuminixDx in English, inspired by Littmann site.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  responsive_framework: ^1.1.1
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  lucide_icons: ^0.257.0
  file_picker: ^10.2.0
  record: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
 
  
